name: Vercel Preview Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  vercel-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Vercel Action - Deploy Preview
        uses: amondnet/vercel-action@v21
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod=false'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
